### ISSUE TITLE
Export events directly to calendar

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/ThaliApp#107]
In GitLab by @se-bastiaan on Jun 3, 2019, 17:33

### One-sentence description

Export events directly to calendar

### Motivation

Make it easy to add an event if you don't want to use an iCal feed.

### Desired functionality

Use the share option of events to open Google Calendar and add it directly to an agenda of choice.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jun 13, 2019, 23:36

Can use https://github.com/vonovak/react-native-add-calendar-event

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Jun 26, 2019, 19:32

Another option would be writing an ical file to disk and opening it I think.

**Comment by thaliawww-service** [comment]
In GitLab by @KiOui on Feb 19, 2020, 20:51

assigned to @KiOui

**Comment by KiOui** [comment]
On adjusting anything on the admin screen (both for events and pizza), the screen pulls down (on iOS).

Fix by altering the global state.
