### ISSUE TITLE
Improve GitHub Actions workflow

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/ThaliApp#134]
### Describe the change
The GitHub Actions workflow can be improved with for example Android builds.

### Motivation
We had this in GitLab but it was removed because it was never working. Before we also had Buddybuild and this has all degraded over time. Now that we are on GitHub we can set this up again.

**Comment by KiOui** [comment]
Maybe add an iOS build as well?

**Comment by se-bastiaan** [comment]
Yes, I already tried something but iOS seems really hard https://github.com/svthalia/ThaliApp/tree/ios-build
