### ISSUE TITLE
Search for Calendar events

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/ThaliApp#97]
In GitLab by rwechel on Feb 2, 2019, 16:26

### One-sentence description
Search for Calendar events.

### Desired behaviour
Since scrolling up is used for refreshing the page, maybe add a search functionality.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 2, 2019, 16:51

Why?

**Comment by thaliawww-service** [comment]
In GitLab by rwechel on Feb 2, 2019, 17:53

Just something that came to mind the other day. I realized I would find this useful after I wanted to change someones attendance status after the event happened. Perhaps a low priority label would be more suitable.
By the way; this is an issue created on personal title

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Feb 2, 2019, 17:58

I just noticed that our new issue templates are not in this repo. We've added a motivation part to it.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on May 30, 2019, 14:27

I think that adding search for events would be easier to implement, since the sectionlist cannot start at a certain position by default. It's not made for such a thing.

**Comment by thaliawww-service** [comment]
In GitLab by rwechel on May 31, 2019, 19:11

Maybe even better :)

**Comment by thaliawww-service** [comment]
In GitLab by @DeD1rk on Nov 6, 2019, 21:33

created merge request !398 to address this issue

**Comment by gijshendriksen** [comment]
@DeD1rk are you still working on this? If not, I'd like to pick it up :innocent:

**Comment by DeD1rk** [comment]
If I recall correctly, it was basically ready to merge when corona struck. I think next week I’ll be doing the tape so feel free to finish it!

**Comment by se-bastiaan** [comment]
It was left in gitlab https://gitlab.science.ru.nl/thalia/ThaliApp/-/merge_requests/398

**Comment by gijshendriksen** [comment]
Cool, thanks!
